name: fyp_application
description: "A new Flutter project."

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  audio_session: ^0.1.19
  file_picker: ^8.0.2
  flutter:
    sdk: flutter
  flutter_localization: ^0.2.0
  flutter_localizations:
    sdk: flutter
  intl: ^0.18.1
  just_audio: ^0.9.37
  permission_handler: ^11.3.1
  provider: ^6.1.2
  record: ^5.0.5
  simple_gradient_text: ^1.3.0
  firebase_core: ^2.30.1
  firebase_storage: ^11.7.4
  cloud_firestore: ^4.17.2
  firebase_auth: ^4.19.4
  google_sign_in: ^6.2.1
  flutter_riverpod: ^2.0.2
  rxdart: ^0.27.7
  http: ^1.2.2
  fpdart: ^1.1.0
  dio: ^5.0.3
  shared_preferences: ^2.2.3
  encrypt: ^5.0.3


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.2
  # riverpod_generator: ^2.4.0
  build_runner: ^2.4.9
  custom_lint: ^0.6.4
  # riverpod_lint: ^2.3.10

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
